name: API Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: '22'
          cache: 'maven'
      - name: Build with Maven, run tests
        run: mvn -B package --file pom.xml